name: accuracy-test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.1.0
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: pip install poetry

      - name: Install Requirements
        run: poetry install

      - name: Run Tests
        run: poetry run pytest tests/ -s
